version: '3.9'

services:
  chrona-app:
    build:
      context: ./chrona-backend
      dockerfile: Dockerfile
    ports:
      - "8008:8000"
    env_file:
      - ./chrona-backend/.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  logging-service:
    build: ./logging-service
    ports:
     - "8001:7000"
    env_file:
      - ./logging-service/.env
    depends_on:
      - redis
      - pushgateway

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway