version: '3.9'

services:
  chrona-app:
    build:
      context: ./chrona-backend
      dockerfile: Dockerfile
    ports:
      - "8008:8000"
    env_file:
      - ./chrona-backend/.env
    ports:
      - 8001:8000