# Generated by Django 5.1.7 on 2025-04-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_email_hmac',
            field=models.CharField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='_first_name_hmac',
            field=models.CharField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='_last_name_hmac',
            field=models.CharField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='_username_hmac',
            field=models.CharField(db_index=True, editable=False, unique=True),
        ),
    ]
