# Generated by Django 5.1.7 on 2025-05-24 18:50

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_email_hmac',
            field=models.CharField(db_index=True, default=None, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='_username_hmac',
            field=models.CharField(db_index=True, default=None, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=utils.fields.EncryptedEmailField(blank=False, default=None, null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=utils.fields.EncryptedCharField(blank=False, default=None, null=False, unique=True),
        ),
    ]
