# Generated by Django 5.1.7 on 2025-05-26 13:24

import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('endpoint', utils.fields.EncryptedTextField(blank=False, null=False, unique=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('p256dh', utils.fields.EncryptedTextField(blank=False, null=False, unique=False)),
                ('auth', utils.fields.EncryptedTextField(blank=False, null=False, unique=False)),
                ('_endpoint_hmac', models.CharField(db_index=True, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'safe_search_fields': ['endpoint'],
            },
        ),
    ]
