# Generated by Django 5.1.7 on 2025-04-22 00:18

import django.db.models.deletion
import utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('browser_notifications_enabled', models.BooleanField(default=True)),
                ('volume_level', models.PositiveIntegerField(default=50)),
                ('vibrate_enabled', models.BooleanField(default=True)),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', utils.fields.EncryptedCharField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('remaining_duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('completed', 'Completed')], max_length=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('_name_hmac', models.CharField(db_index=True, editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('Timer',),
                'verbose_name_plural': 'Timers',
                'ordering': ['-updated_at'],
                'safe_search_fields': ['name'],
            },
        ),
    ]
