# Generated by Django 5.1.7 on 2025-05-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_timers_remaining_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timers',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('completed', 'Completed'), ('inactive', 'Inactive')], max_length=10),
        ),
    ]
