# Generated by Django 5.1.7 on 2025-05-23 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0003_alter_timers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timers',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
