# Generated by Django 5.1.7 on 2025-06-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0004_alter_timers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timers',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('completed', 'Completed'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
