global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: "logging-service"
    static_configs:
      - targets: ['logging-service:7000']

  - job_name: "chrona-app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ['chrona-app:8000']