# Generated by Django 5.1.7 on 2025-05-26 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('timer_complete_email', 'Timer Complete Email'), ('timer_push_notify', 'Timer Push Notification')], max_length=50)),
                ('related_model', models.CharField(max_length=100)),
                ('related_obj_id', models.CharField(max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_registry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
