name: Build and Deploy Logging Service

on:
  push:
    paths:
      - 'logging-service/**'
      - 'infra/terraform/logging-service/**'
      - '.github/workflows/deploy-logging-service.yml'
    branches: [ "develop"]
    tags: [ "*" ]
  workflow_dispatch:

concurrency:
  group: "chrona-logging-service"
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set-env.outputs.ENVIRONMENT }}
    steps:
      - name: Determine Environment
        id: set-env
        run: |
          REF_TYPE="${GITHUB_REF#refs/*/}"
          REF_NAME="${GITHUB_REF##*/}"

          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            if [ "$REF_NAME" = "develop" ]; then
              echo "ENVIRONMENT=logging-service-dev" >> $GITHUB_OUTPUT
            fi
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "ENVIRONMENT=logging-service-prod" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Get Env Variables
        run: |
          echo "Environment: ${{ steps.set-env.outputs.ENVIRONMENT }}"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: ${{ needs.prepare.outputs.ENVIRONMENT }}

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}


    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 🐳 Build and Push Logging Service Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./logging-service
          dockerfile: ./logging-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chrona-logging-service:latest

      - name: 🔐 Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🧱 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: ✅ Terraform Init
        working-directory: ./infra/terraform/logging-service
        run: |
          terraform init -upgrade \
            -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.TFSTATE_KEY }}"

      - name: ✅ Terraform Plan
        working-directory: ./infra/terraform/logging-service
        run: |
          echo "Running Terraform Plan..."
          terraform plan -refresh=false -no-color \
            -var "resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
            -var "location=${{ secrets.LOCATION }}" \
            -var "container_app_env_name=${{ secrets.CONTAINER_APP_ENV_NAME }}" \
            -var "app_name=${{ secrets.CONTAINER_APP_NAME }}" \
            -var "logging_service_image=ghcr.io/${{ github.repository_owner }}/chrona-logging-service:latest" \
            -var "registry_password=${{ secrets.GHCR_TOKEN }}" \
            -var "registry_username=${{ github.repository_owner }}" \
            -var "min_replicas=${{ secrets.MIN_REPLICAS }}"

      - name: ✅ Terraform Apply
        working-directory: ./infra/terraform/logging-service
        run: |
          terraform apply -auto-approve \
            -var "resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
            -var "location=${{ secrets.LOCATION }}" \
            -var "container_app_env_name=${{ secrets.CONTAINER_APP_ENV_NAME }}" \
            -var "app_name=${{ secrets.CONTAINER_APP_NAME }}" \
            -var "logging_service_image=ghcr.io/${{ github.repository_owner }}/chrona-logging-service:latest" \
            -var "registry_password=${{ secrets.GHCR_TOKEN }}" \
            -var "registry_username=${{ github.repository_owner }}" \
            -var "min_replicas=${{ secrets.MIN_REPLICAS }}"

      - name: 🔑 Fetch and Inject Vault Secrets into Container App
        env:
          VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          CONTAINER_APP_NAME: ${{ secrets.CONTAINER_APP_NAME }}
        run: |
          echo "🔎 Fetching secrets from Key Vault..."
          secrets=$(az keyvault secret list --vault-name "$VAULT_NAME" --query "[].name" -o tsv)
          
          echo "🚀 Preparing secrets injection..."
          secrets_args=""
          
          for secret in $secrets
          do
            lowercase_secret="${secret,,}"
          
            # Fetch secret value
            value=$(az keyvault secret show --vault-name "$VAULT_NAME" --name "$secret" --query "value" -o tsv)
          
            # Add to secrets_args (quote value to handle spaces/special chars)
            secrets_args="$secrets_args $lowercase_secret=$value"
          done
          
          echo "Injecting all secrets in single batch..."
          az containerapp secret set \
            --name "$CONTAINER_APP_NAME" \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --secrets $secrets_args

      - name: 🔗 Bind Secrets to Environment Variables
        env:
          VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          CONTAINER_APP_NAME: ${{ secrets.CONTAINER_APP_NAME }}
        run: |
          echo "🔗 Binding secrets to environment variables..."
          existing_secrets=$(az containerapp secret list --name "$CONTAINER_APP_NAME" --resource-group "$RESOURCE_GROUP_NAME" --query "[].name" -o tsv)
          
          env_args=""
          for secret in $existing_secrets
          do
            # Sanitize secret name: replace - with _
            env_var_name=$(echo "$secret" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
            env_args="$env_args $env_var_name=secretref:$secret"
          done
          
          az containerapp update \
            --name "$CONTAINER_APP_NAME" \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --set-env-vars $env_args
        
          echo "✅ Environment variables updated."


      - name: 🌐 Output Logging Service URL
        env:
          CONTAINER_APP_NAME: ${{ secrets.LOGGING_CONTAINER_APP_NAME }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        run: |
          echo "🔍 Fetching logging service URL..."
          az containerapp show \
            --name "$CONTAINER_APP_NAME" \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --query properties.configuration.ingress.fqdn \
            -o tsv
